# Sourcing external config files

# User Configs
$UserConfigsPath = $HOME/.config/hypr/Configs

source=$UserConfigsPath/Startup_Apps.conf
source=$UserConfigsPath/ENVariables.conf
source=$UserConfigsPath/Monitors.conf
# source= $UserConfigs/Laptops.conf
# source= $UserConfigs/LaptopDisplay.conf
source=$UserConfigsPath/WindowRules.conf
source=$UserConfigsPath/UserKeybinds.conf
source=$UserConfigsPath/WorkspaceRules.conf
source=$UserConfigsPath/Plugins.conf
source=$UserConfigsPath/UserSettings.conf
