$mainMod = SUPER

exec-once = slack
exec-once = env PATH=/usr/local/google-cloud-sdk/bin:$PATH /home/alex/Programs/cloud-sql-proxy -g 'dataproduction-prod:europe-west1:prod-dtdev2?port=5438' &> /tmp/proxy_dataprod.log # Activate proxy for database
exec-once = env PATH=/usr/local/google-cloud-sdk/bin:$PATH /home/alex/Programs/cloud-sql-proxy -g 'green-vision-io:europe-west1:greenvision-io-visionr?port=5436' &> /tmp/proxy_green.log # Activate proxy for database
exec-once = blueman-applet
exec-once = uv run --project ~/Documents/pure-black/ ~/Documents/pure-black/widgets/bar.py &> /tmp/bar.log
monitor = eDP-1, preferred, 0x0, 1.25
monitor = HDMI-A-1, preferred, -256x-1152, 1.25

# monitor = HDMI-A-1, preferred, 1536x0, 1

bind = $mainMod, G, exec, swaync-client -t
