# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #ECDCE2
background         #000005
cursor             #ECDCE2

active_tab_foreground     #000005
active_tab_background     #ECDCE2
inactive_tab_foreground   #ECDCE2
inactive_tab_background   #000005

active_border_color   #ECDCE2
inactive_border_color #000005
bell_border_color     #252632

color0      #000005
color1		#252632
color2		#2C2B37
color3		#5E4D5A
color4		#5C5B6C
color5		#906F7D
color6		#977482
color7		#DCC4CE
color8		#9A8A90
color9		#313343
color10		#3B394A
color11		#7D6778
color12		#7A7A90
color13		#C094A7
color14		#CA9BAD
color15		#DCC4CE
